# Generated by Django 3.2.25 on 2025-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_rename_colour_listing_wine_colour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
