# Generated by Django 3.2.25 on 2025-05-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20250316_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
